services:
  - type: web
    name: encryptex
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app --workers 2 --bind 0.0.0.0:$PORT"
    plan: free
    autoDeploy: true
